apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: hostpath
      mountPath: /host_proc
    securityContext:
      privileged: true
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-168-130
  volumes:
  - name: hostpath
    hostPath:
      # directory location on host
      path: /proc
      # this field is optional
      type: Directory
